version: '3.2'

services:
  postgresql:
    container_name: postgresql_postgresql
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlineshop
    ports:
      - "5431:5432"

  flyway_postgresql:
    image: boxfuse/flyway
    command: "clean migrate"
    depends_on:
      - postgresql
    volumes:
      - $PWD/database/flyway/config:/flyway/conf
      - $PWD/database/flyway/sql-scripts:/flyway/sql