spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5431/onlineshop
    username: postgres
    password: postgres
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/